// Editing tool pages: crop, rotate, flip, watermark, filters ...

export const EDIT_PAGES = [
  {
    slug: 'crop-image',
    tool: 'crop',
    category: 'edit',
    icon: 'crop',
    name: 'Crop Image',
    title: 'Crop Image Online Free – Cut Photo to Any Size or Ratio',
    description: 'Crop images online for free. Drag to select the area, choose 1:1, 4:3, 16:9 or free ratio, and download instantly. Works on mobile, no upload.',
    h1: 'Crop Image Online',
    intro: 'Cut out exactly the part of the picture you want. Drag the box, pick a ratio like 1:1 or 16:9, or type the exact size in pixels.',
    howTitle: 'crop an image',
    steps: [
      'Upload the image you want to crop.',
      'Drag the box to move it and pull the corners to resize it.',
      'Choose an aspect ratio (1:1, 4:3, 16:9…) or type the exact width and height.',
      'Click "Crop & download".',
    ],
    faq: [
      { q: 'How do I crop a photo into a square?', a: 'Choose the 1:1 ratio, position the box and click Crop.' },
      { q: 'Does cropping reduce quality?', a: 'No. The cropped area keeps the original pixels; only the parts outside the box are removed.' },
      { q: 'Can I crop on my phone?', a: 'Yes. You can drag the box and handles with your finger.' },
    ],
    related: ['resize-image', 'rotate-image', 'compress-image'],
  },
  {
    slug: 'rotate-image',
    tool: 'rotate',
    category: 'edit',
    icon: 'rotate',
    name: 'Rotate Image',
    title: 'Rotate Image Online – Rotate Photo 90°, 180° or Any Angle',
    description: 'Rotate images online by 90, 180 or 270 degrees or any custom angle. Batch rotate JPG, PNG and WebP photos and download as ZIP. Free and private.',
    h1: 'Rotate Image',
    intro: 'Fix sideways or upside-down photos in one click. Rotate many images at once, or straighten a picture by any angle.',
    howTitle: 'rotate an image',
    steps: ['Upload one or more images.', 'Choose 90° clockwise, 180° or 90° anti-clockwise (or a custom angle in Advanced options).', 'Click "Rotate images" and download.'],
    faq: [
      { q: 'Why is my photo sideways?', a: 'Phones store the camera orientation separately. Some apps ignore it, so the picture appears rotated. Rotating it here saves the pixels in the correct direction.' },
      { q: 'Can I rotate by a custom angle?', a: 'Yes — open Advanced options and use the Custom angle slider to straighten a tilted horizon.' },
    ],
    related: ['flip-image', 'crop-image', 'resize-image'],
  },
  {
    slug: 'flip-image',
    tool: 'rotate',
    options: { flipOnly: true, angle: 0, flipH: true },
    category: 'edit',
    icon: 'flip',
    name: 'Flip Image',
    title: 'Flip Image Online – Mirror Photo Horizontally or Vertically',
    description: 'Flip or mirror images online. Flip photos horizontally or vertically in one click, batch process and download free. No upload required.',
    h1: 'Flip / Mirror Image',
    intro: 'Mirror a selfie, reverse text in a photo, or flip a picture upside down. Works on many images at once.',
    howTitle: 'flip an image',
    steps: ['Upload your image(s).', 'Tick "Flip horizontally" to mirror, or "Flip vertically" to turn upside down.', 'Click "Flip images" and download.'],
    faq: [
      { q: 'How do I un-mirror a selfie?', a: 'Upload it and keep "Flip horizontally" ticked. The text and your face will be shown the right way round.' },
      { q: 'Is quality lost when flipping?', a: 'No, flipping simply rearranges the pixels.' },
    ],
    related: ['rotate-image', 'crop-image'],
  },
];
