// Editing tool pages: crop, rotate, flip, watermark, filters ...

export const EDIT_PAGES = [
  {
    slug: 'crop-image',
    tool: 'crop',
    category: 'edit',
    icon: 'crop',
    name: 'Crop Image',
    title: 'Crop Image Online Free – Cut Photo to Any Size or Ratio',
    description: 'Crop images online for free. Drag to select the area, choose 1:1, 4:3, 16:9 or free ratio, and download instantly. Works on mobile, no upload.',
    h1: 'Crop Image Online',
    intro: 'Cut out exactly the part of the picture you want. Drag the box, pick a ratio like 1:1 or 16:9, or type the exact size in pixels.',
    howTitle: 'crop an image',
    steps: [
      'Upload the image you want to crop.',
      'Drag the box to move it and pull the corners to resize it.',
      'Choose an aspect ratio (1:1, 4:3, 16:9…) or type the exact width and height.',
      'Click "Crop & download".',
    ],
    faq: [
      { q: 'How do I crop a photo into a square?', a: 'Choose the 1:1 ratio, position the box and click Crop.' },
      { q: 'Does cropping reduce quality?', a: 'No. The cropped area keeps the original pixels; only the parts outside the box are removed.' },
      { q: 'Can I crop on my phone?', a: 'Yes. You can drag the box and handles with your finger.' },
    ],
    related: ['resize-image', 'rotate-image', 'compress-image'],
  },
  {
    slug: 'rotate-image',
    tool: 'rotate',
    category: 'edit',
    icon: 'rotate',
    name: 'Rotate Image',
    title: 'Rotate Image Online – Rotate Photo 90°, 180° or Any Angle',
    description: 'Rotate images online by 90, 180 or 270 degrees or any custom angle. Batch rotate JPG, PNG and WebP photos and download as ZIP. Free and private.',
    h1: 'Rotate Image',
    intro: 'Fix sideways or upside-down photos in one click. Rotate many images at once, or straighten a picture by any angle.',
    howTitle: 'rotate an image',
    steps: ['Upload one or more images.', 'Choose 90° clockwise, 180° or 90° anti-clockwise (or a custom angle in Advanced options).', 'Click "Rotate images" and download.'],
    faq: [
      { q: 'Why is my photo sideways?', a: 'Phones store the camera orientation separately. Some apps ignore it, so the picture appears rotated. Rotating it here saves the pixels in the correct direction.' },
      { q: 'Can I rotate by a custom angle?', a: 'Yes — open Advanced options and use the Custom angle slider to straighten a tilted horizon.' },
    ],
    related: ['flip-image', 'crop-image', 'resize-image'],
  },
  {
    slug: 'flip-image',
    tool: 'rotate',
    options: { flipOnly: true, angle: 0, flipH: true },
    category: 'edit',
    icon: 'flip',
    name: 'Flip Image',
    title: 'Flip Image Online – Mirror Photo Horizontally or Vertically',
    description: 'Flip or mirror images online. Flip photos horizontally or vertically in one click, batch process and download free. No upload required.',
    h1: 'Flip / Mirror Image',
    intro: 'Mirror a selfie, reverse text in a photo, or flip a picture upside down. Works on many images at once.',
    howTitle: 'flip an image',
    steps: ['Upload your image(s).', 'Tick "Flip horizontally" to mirror, or "Flip vertically" to turn upside down.', 'Click "Flip images" and download.'],
    faq: [
      { q: 'How do I un-mirror a selfie?', a: 'Upload it and keep "Flip horizontally" ticked. The text and your face will be shown the right way round.' },
      { q: 'Is quality lost when flipping?', a: 'No, flipping simply rearranges the pixels.' },
    ],
    related: ['rotate-image', 'crop-image'],
  },
];

EDIT_PAGES.push({
  slug: 'add-watermark-to-image',
  tool: 'watermark',
  category: 'edit',
  icon: 'watermark',
  name: 'Add Watermark',
  title: 'Add Watermark to Image Online Free – Text & Logo Watermark',
  description: 'Add a text or logo watermark to photos online. Choose position, size and opacity, or tile it across the image. Batch watermark many photos free.',
  h1: 'Add Watermark to Photos',
  intro: 'Protect your photos with a text or logo watermark. Place it in a corner or repeat it across the whole image — then process a whole batch at once.',
  howTitle: 'add a watermark to an image',
  steps: [
    'Upload the photos you want to protect.',
    'Type your watermark text and choose the size, opacity and position.',
    'Optionally add a logo in Advanced options.',
    'Click "Add watermark" and download the results.',
  ],
  faq: [
    { q: 'Can I watermark many photos at once?', a: 'Yes. All uploaded photos get the same watermark and you can download them together as a ZIP.' },
    { q: 'Can I use my logo?', a: 'Yes. Open Advanced options and pick a PNG logo — transparent PNGs work best.' },
    { q: 'Which position is hardest to remove?', a: '"Repeat across image" tiles the watermark diagonally over the whole photo, which is the hardest to crop out.' },
  ],
  related: ['compress-image', 'resize-image', 'crop-image'],
});

EDIT_PAGES.push(
  {
    slug: 'photo-filters',
    tool: 'filters',
    category: 'edit',
    icon: 'filter',
    name: 'Photo Filters & Adjust',
    title: 'Photo Editor Online – Brightness, Contrast & Filters Free',
    description: 'Edit photos online: adjust brightness, contrast and saturation, or apply B&W, vintage and vivid filters with live preview. Batch edit and download free.',
    h1: 'Photo Filters & Adjustments',
    intro: 'Brighten dark photos, boost colours or give pictures a vintage or black & white look — with a live preview, then apply it to every photo at once.',
    howTitle: 'edit a photo',
    steps: ['Upload one or more photos.', 'Pick a quick look or move the sliders while watching the preview.', 'Click "Apply to all images" and download.'],
    faq: [
      { q: 'How do I brighten a dark photo?', a: 'Increase Brightness to about 120–140% and Contrast slightly. Watch the preview until it looks right.' },
      { q: 'Are the settings applied to every image?', a: 'Yes. All images in the list get the same adjustments, which is perfect for a consistent look.' },
    ],
    related: ['black-and-white-image', 'blur-image', 'compress-image'],
  },
  {
    slug: 'black-and-white-image',
    tool: 'filters',
    options: { look: 'bw' },
    category: 'edit',
    icon: 'filter',
    name: 'Black & White Converter',
    title: 'Convert Image to Black and White Online – Grayscale Free',
    description: 'Turn colour photos into black and white (grayscale) online in one click. Adjust contrast, batch convert and download free. No upload needed.',
    h1: 'Convert Image to Black & White',
    intro: 'Give your photos a classic black and white look instantly. The B&W filter is already applied — just upload, preview and download.',
    howTitle: 'convert an image to black and white',
    steps: ['Upload your photos.', 'The black & white look is already selected — tweak contrast if you like.', 'Click "Apply to all images" and download.'],
    faq: [{ q: 'Is grayscale the same as black and white?', a: 'In photos, yes — grayscale keeps all the shades of grey between black and white, which is what people usually mean by a black and white photo.' }],
    related: ['photo-filters', 'blur-image'],
  },
);

EDIT_PAGES.push({
  slug: 'blur-image',
  tool: 'filters',
  options: { look: 'blur' },
  category: 'edit',
  icon: 'blur',
  name: 'Blur Image',
  title: 'Blur Image Online Free – Add Blur Effect to Photos',
  description: 'Blur images online for free. Add a soft or strong blur to photos for backgrounds, wallpapers and privacy. Live preview, batch processing, no upload.',
  h1: 'Blur Image Online',
  intro: 'Soften a whole photo for a dreamy background or wallpaper. Control the blur strength with a slider and see the result live.',
  howTitle: 'blur an image',
  steps: ['Upload your photo.', 'Move the Blur slider until you like the preview.', 'Click "Apply to all images" and download.'],
  faq: [
    { q: 'How strong can the blur be?', a: 'Up to 20 pixels. For very large photos, a higher value gives a softer look.' },
    { q: 'Can I blur only part of an image?', a: 'This tool blurs the whole picture. Crop first if you only need part of it.' },
  ],
  related: ['photo-filters', 'crop-image', 'add-watermark-to-image'],
});

EDIT_PAGES.push({
  slug: 'merge-images',
  tool: 'merge',
  category: 'edit',
  icon: 'merge',
  name: 'Merge Images',
  title: 'Merge Images Online – Combine Photos Side by Side or Grid',
  description: 'Combine multiple images into one online. Put photos side by side, stack them vertically or make a grid collage with spacing. Free, no upload needed.',
  h1: 'Merge Images into One',
  intro: 'Join two or more photos into a single image — side by side, one above the other, or as a neat grid collage.',
  howTitle: 'merge images',
  steps: ['Upload two or more images.', 'Choose Side by side, Stacked or Grid and adjust the spacing.', 'Click "Download merged image".'],
  faq: [
    { q: 'How do I put two photos side by side?', a: 'Upload both photos and keep "Side by side" selected. They are scaled to the same height automatically.' },
    { q: 'Can I merge front and back of an ID card?', a: 'Yes — choose "Stacked" to put the front above the back in one image, which many forms ask for.' },
  ],
  related: ['image-to-pdf', 'resize-image', 'crop-image'],
});

EDIT_PAGES.push({
  slug: 'circle-crop-image',
  tool: 'crop',
  options: { shape: 'circle', ratio: '1' },
  category: 'edit',
  icon: 'crop',
  name: 'Circle Crop',
  title: 'Circle Crop Image Online – Make Round Profile Picture Free',
  description: 'Crop images into a circle online. Make round profile pictures and logos with a transparent background (PNG). Free, works on mobile, no upload needed.',
  h1: 'Circle Crop Image',
  intro: 'Turn any photo into a perfectly round picture with a transparent background — great for profile photos, logos and stickers.',
  howTitle: 'crop an image into a circle',
  steps: ['Upload your photo.', 'Move and resize the circle over the part you want to keep.', 'Click "Crop & download" to save a round PNG with a transparent background.'],
  faq: [
    { q: 'Why is the result a PNG?', a: 'Only PNG keeps the transparent corners around the circle. JPG would fill them with a solid colour.' },
    { q: 'Can I make an oval?', a: 'Choose the "Free" ratio after selecting Circle to stretch the shape into an oval.' },
  ],
  related: ['crop-image', 'whatsapp-dp-resizer', 'resize-image'],
});
